using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Bartin
{
    public partial class bartin_lable_bilgileri : Form
    {
        public bartin_lable_bilgileri()
        {
            InitializeComponent();
            tarihVeKulturtextBox.Text = "Batı Karadeniz Bölgesi’nde yer alan Bartın İli’nin, kuzeyini 59 km.lik sahil şeridiyle Karadeniz çevrelerken, doğuda Kastamonu, doğu ve güneyde Karabük, batıda ise Zonguldak illeri çevirmektedir. Bartın; doğu, batı ve kuzeyden yüksekliği 2000 m.yi geçmeyen dağlarla çevrilidir. Dağlar, yüksek olmamakla birlikte oldukça dik, sahillere doğru sarp ve kayalıktır. En yüksek nokta Keçikıran Tepesi’dir (1619 m.). Aladağ, Kocadağ, Karadağ, Kayaardı, Karasu ve Arıt dağları ise bölgenin en önemli dağlarıdır. Kent merkezini batıdan Aladağ, kuzeyden Karasu dağları ve doğudan Arıt dağları kuşatmaktadır. Bartın Irmağı ve kolları tarafından derin bir biçimde parçalanan arazi çok engebeli bir görünümdedir. Irmağın genişlediği alanlarda ve dağların oldukça dik yamaçları arasında dar ve derin vadiler yer alır. Kent merkezlerine inildikçe düz ovalar artmaktadır.\r\n\r\n" +
                "Bartın’ın en önemli akarsuyu, Antik Çağda Parthenios adı ile anılan ve kente adını veren Bartın ırmağıdır.Bartın ırmağının iki ana kolunu oluşturan Kocaçay ve Kocanazçayı, Bartın merkezinde Gazhane Burnu’nda birleşip Boğaz mevkiinde Karadeniz’e ulaşır. Kocanazçayı; güneyden doğup Kozcağız’dan kuzeye doğru akarken, 107 km.uzunluğundaki Kocaçay; Kastamonu’dan gelip Ulus’tan geçen Göksu ve Eldeş Çayları(Ulus Çayı) ile bunlara katılan derelerden oluşur.Arıt ve Mevren Derelerinden oluşan Kozlu Çayı ile birleşen Kışla Deresi, Akpınar ve Karaçay Dereleri Kocaçay’ı besleyen akarsulardır.Kapısuyu ve Tekkeönü Dereleri ile Ulus-Uluyayla’yı sulayan Ovaçayı ve İnönü Dereleri ise diğer önemli akarsularıdır.\r\n\r\n" +
                "Yüzölçümü 2143 km2’olup, denizden yüksekliği 25 m.dir.İlin toplam nüfusu ise 184.178’dir.\r\n\r\n" +
                "İlin ekonomisi, tarım, hayvancılık ve ormancılığa dayanmaktadır.Bölgede yetiştirilen tarımsal ürünler, buğday, arpa, mısır, yulaf, fasulye, ayçiçeği, soğan, patates, yonca, fiğdir. Son yıllarda seracılık gelişim göstermiştir.Bartın’ın 2140 km²’lik toplam arazi varlığının % 46’sını ormanlar kaplamaktadır.İlin ormanları eskiden beri ekonominin temel sektörlerinden birini oluşturmuştur.Osmanlı Devletinin Gelibolu tersanesini kurmak için teşebbüse geçtiği 1402 yılından itibaren kerestecilik faaliyetinin başladığı, Osmanlı donanmasının kadırga ve kalyonlarının Bartın, Amasra ve Kurucaşiledeki tersanelerde yapıldığı ve1914 yılında Süveyş Kanalı takimatında kullanılmak üzere Bartın’dan Mısır’ın İskenderiye limanına kereste sevk edildiği tarihi kayıtlarda bulunmaktadır. 600 metre yüksekliğe kadar olan bölümde defne, meşe, kayın, kocayemiş, ardıç, 600 - 1000 metre yükseltili alanda meşe, kayın gürgen, 1000 - 1500 ve daha yukarı kesimlerde ise kayın kestane ve çam ağaçlarından oluşan il ormanları Bartın merkez ve Ulus ilçesindeki iki ayrı işletme müdürlüğü tarafından işletilmektedir.\r\n\r\n" +
                "“Parthenia\"dan Bartın’a dönüşen adın kaynağı “Parthenios\"dur.Bartın Irmağının antik çağdaki adı olan Parthenios; Yunan mitolojisinde, Tanrıların Babası Okenus'un çocukları olan yüzlerce tanrıdan birisi ve “Sular Tanrısı “ dır. Antik çağda Parthenios adı verilen Bartın Irmağının kenarında kurulan Parthenia kentinin adı zamanla Bartın'a dönüşmüştür.\r\n\r\n" +
                "Bartın'ın tarihçesi ile ilgili kesin bilgi bulunmamakla birlikte, Bartın’ın ilk sahiplerinin, M.Ö.XIV.yüzyılda Gaskalar ve M.Ö.XIII.yüzyılda Hititler olduğu kabul edilmekte, daha sonra Bolu yöresine yerleşen Bitinyalılar ile Kastamonu yöresinde hüküm süren Paflagonyalıların, sınırlarını Parthenios’a kadar Genişlettikleri böylece Bartın Topraklarının bu iki egemenliğin sınırları içinde yer aldığı bilinmektedir.M.Ö.XII.yüzyıl sonlarında Bithynie Bölgesindeki Bartın Friglerin, Paplagonie Bölgesindeki Amasra Fenikelilerin eline geçmiş, Fenikeliler; Amasra (Sesamos), Ereğli (Heraklia), Sinop(Sinope) ve Tekkeönü’nde (Kromna) ilk Sayda Kolonilerini oluşturmuşlardır. Bartın ve çevresi,M.Ö.VII.yüzyıl sonlarında Kimmerlerin, M.Ö.VI.yüzyılda Lidyalıların, M.Ö.547 yılında da Perslerin egemenliği altına girmiştir.\r\n\r\n" +
                "M.Ö. 334 yılında, Makedonya Kralı İskender, Perslerin hakimiyetine son vererek bölgenin sahibi olmuş ve Bartın ve Ulus’un yönetimini General Eumenes’e, Amasra ve Tekkeönü’nün yönetimini de Fridya Satrabına bırakmıştır .Ancak, Amasra yönetimi M.Ö.302 - 286 yılları arasında el değiştirerek Kraliçe Amastris tarafından yönetilmeye başlandı.M.Ö.XII.yüzyıldan beri Sesamos adıyla anılan kent 16 yıllık Kraliçe Amastris Döneminden sonra kraliçenin adını almıştır.Bu dönemde; Kromna(Tekkeönü), Tios(Filyos - Hisarönü) ve Kyteros(Gideros) sitelerinden oluşan Symoikismos Siteler Birliğine Başkent olmuştur.M.Ö.286 yılında Kraliçe Amastris,oğulları tarafından bindiği gemi batırılmak suretiyle öldürülünce kent yeniden Eumenes’ce yönetilmeye başlanmış, Amasra ve Bartın çevresi yöredeki savaşlar sonrasında M.Ö.279 yılında Pontus Krallığının egemenliğine girmiştir.M.Ö.70 yılında Anadolu’ya giren Romalılar Pontus Krallığının Egemenliğine son vererek yöreye egemen olmuşlardır.Roma döneminde Bitinya ve Pontusun Paflagonya'daki bölümü Bitinya-Pontus eyaleti olarak Satraplıkla yönetilmeye başlanmış, .Amasra bu eyaletin Pontus bölümü başkenti olmuştur.\r\n\r\n" +
                "M.S.395 yılına kadar Roma İmparatorluğu’nun, Roma - Bizans bölünmesi üzerine de Bizansın payına düşen Bartın ve çevresi uzun yıllar Bizans’ın hakimiyetinde kaldı.\r\n\r\n" +
                "Bartın ve çevresi M.Ö. 390 yıllarında Hazar hükümdarı Sahip Han komutasındaki Peçenek ve Kumanların, M.S. 798 yıllarında Abdülmelik komutasındaki Arapların, 800 yıllarında Selçukluların ve 865 yıllarında da Rusların yoğun akınlarına uğramıştır. Kutalmışoğlu Süleyman Bey’in Komutanlarından Emir Karatigin 1084 yılında Sinop, Çankırı, Kastamonu ve Zonguldak’ı alarak yörede Bartın, Ulus, Eflani, Safranbolu ve Devrek’i de kapsayan bir Türk Emirliği kurdu.Ancak, 1086 yılında Süleyman Bey’in ölümü ve 1096 yılında başlayan 1.Haçlı Seferleri, Kuzeybatı Anadolu’ya yerleşen Türkler açısından ciddi sıkıntılar yaratmış, Haçlı müttefiklerle Bizans arasında yapılan anlaşma sonrasında başta Amasra, Sinop ve Ereğli olmak üzere İstanbul’dan Samsun’a kadar tüm Karadeniz sahili yeniden Bizans’ın hakimiyetine girmiştir.Bartın ve çevresi ise Bizans’tan sonra XI.yüzyıl sonlarında Anadolu Selçuklularının eline geçmiştir. 200 yıllık Selçuklu egemenliğinden sonra 1326’da Kastamonu yöresine hakim olan Candaroğulları Beyliği ve 1392’den itibaren de Osmanlı İmparatorluğu topraklarına dahil olmuştur. 1402 yılında yapılan Ankara savaşı sonunda bir ara İsfendiyaroğlu Beyliği’nin eline geçen kent 1461 yılında tekrar Osmanlı Devleti egemenliğine girmiştir.\r\n\r\n" +
                "Bartın,Osmanlı döneminin 1460 - 1692 yılları arasında Anadolu Beylerbeyliği’ne bağlı Bolu Sancağı sınırları içinde yer almış, Bolu Sancağının kaldırılmasıyla 1692 - 1811 yılları arasında Voyvodalıkla yönetilen Bartın, 1811 yılında da Kastamonu Vilayetine bağlı olarak yeniden kurulan Bolu Sancağına bağlanmıştır.\r\n\r\n" +
                "Bu dönemde ticari potansiyeliyle bölgenin Pazar yeri olan ve Oniki Divan adını alan Bartın, 1867 yılında ilçe oldu. 1920 yılında Zonguldak Mutasarrıflığına bağlanan Bartın’ın 1924 yılında Zonguldak’ın il olmasıyla birlikte bu ilin ilçesi haline gelmiştir. 1991 tarihinde de il statüsüne kavuşmuştur.\r\n\r\n" +
                "Bartın’da günümüze gelebilen eserler, Amasra’daki Roma dönemi tiyatrosunun cavea ve skenesi yıkılmış, giriş kapısına ait kalıntılar, Roma dönemine ait nekropol, bouleuterion’un duvar kalıntıları, akropol surlarına ait bazı duvar parçaları, Roma dönemine ait yer altı galerileri, Roma dönemi çarşısından bölümler, Roma dönemine ait rıhtım ve dalgakıran, Büyüktepe’deki inziva mağarası, Tavşan Adası’nda Bizans dönemine ait kilise kalıntıları, Tekkeönü Köyü’ndeki kaleye ait kalıntılar, Bizans dönemine ait Amasra Kalesi, Merkez ilçe sınırları içindeki Güzelcehisar Şarköy ve Fırınlı Köylerinde, Ceneviz Kale kalıntıları; Osmanlı döneminden kalma Fatih Camisi, İçkale Mescidi, Halil Bey Camisi(Yukarı Cami) (1872), İbrahimpaşa Camisi(Orta Cami), Şadırvan Camisi(Aşağı Cami) (1903 - 1905), Şimşirli Baba Camisi Hz.Peygamber’in sancaktarı Ebu Derda Hazretlerine ait olduğu söylenen Ebu Derda Türbesi, Aya Nikola Kilisesi(1319), Amasra Küçüktepe Martryumu bulunmaktadır.\r\n\r\n" +
                "Ayrıca Taşhan(1832 - 1835), Dervişoğlu Hanı(1897), Osmanlı hamam kalıntıları, Şehir Hamamı(1447), Kemer Köprü(1872), Orduyeri(Kışla) Köprüsü(1887), Bizans döneminden kalma Kemere Köprü, Roma dönemine ait Kemerdere Köprüsü ve Osmanlı sivil mimarisine ait ev ve konak örnekleri bulunmaktadır.";
        }

        private void backButton_Click(object sender, EventArgs e)
        {
            sehirForm sehirForm = new sehirForm();
            Hide();
            sehirForm.Show();
        }

        private void bartin_lable_bilgileri_FormClosing(object sender, FormClosingEventArgs e)
        {
            Application.Exit();
        }
    }
}
